//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminJournal
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Cost { get; set; }
        public string Comment { get; set; }
        public int Car_Id { get; set; }
        public Nullable<int> TypeOfCost_Id { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual TypeOfCost TypeOfCost { get; set; }
    }
}
