//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.AdminJournal = new HashSet<AdminJournal>();
            this.DriverJournal = new HashSet<DriverJournal>();
        }
    
        public int Id { get; set; }
        public string Regnr { get; set; }
        public int OriginalMileage { get; set; }
        public Nullable<int> Colour_Id { get; set; }
        public int CarType_Id { get; set; }
        public Nullable<int> Year_Id { get; set; }
        public int FuelType_Id { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminJournal> AdminJournal { get; set; }
        public virtual CarType CarType { get; set; }
        public virtual Colour Colour { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual Year Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverJournal> DriverJournal { get; set; }
        public virtual Car Car1 { get; set; }
        public virtual Car Car2 { get; set; }
    }
}
