//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverJournal
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal FuelAmount { get; set; }
        public decimal PricePerUnit { get; set; }
        public decimal TotalPrice { get; set; }
        public int Driver_Id { get; set; }
        public int Car_Id { get; set; }
        public int FuelType_Id { get; set; }
        public int mileage { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
        public virtual FuelType FuelType { get; set; }
    }
}
