//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WpfprojectEntities : DbContext
    {
        public WpfprojectEntities()
            : base("name=WpfprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminJournal> AdminJournal { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarType> CarType { get; set; }
        public virtual DbSet<Colour> Colour { get; set; }
        public virtual DbSet<DriverJournal> DriverJournal { get; set; }
        public virtual DbSet<FuelType> FuelType { get; set; }
        public virtual DbSet<TypeOfCost> TypeOfCost { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Year> Year { get; set; }
    }
}
